let students = [
  {
    id: 1,
    first_name: "Yorke",
    last_name: "Aasaf",
    email: "yaasaf0@gmpg.org",
    gender: "Male",
    "password ": "uN4{7L_a",
  },
  {
    id: 2,
    first_name: "Sofie",
    last_name: "Clementucci",
    email: "sclementucci1@unblog.fr",
    gender: "Female",
    "password ": "iJ6(1c{AX>B",
  },
  {
    id: 3,
    first_name: "Mirna",
    last_name: "Ower",
    email: "mower2@dedecms.com",
    gender: "Non-binary",
    "password ": 'lZ8}9."/.y{',
  },
  {
    id: 4,
    first_name: "Freddi",
    last_name: "Aylott",
    email: "faylott3@spiegel.de",
    gender: "Female",
    "password ": "gY1&HBuTq!",
  },
  {
    id: 5,
    first_name: "Aimil",
    last_name: "Shimmings",
    email: "ashimmings4@cdbaby.com",
    gender: "Genderqueer",
    "password ": "gX7)unBM}m0Q",
  },
  {
    id: 6,
    first_name: "Brig",
    last_name: "MacCarter",
    email: "bmaccarter5@last.fm",
    gender: "Male",
    "password ": "tV8~?%nn.''0w`t",
  },
  {
    id: 7,
    first_name: "Claudian",
    last_name: "Escott",
    email: "cescott6@aol.com",
    gender: "Male",
    "password ": "gG9+4DPZ",
  },
  {
    id: 8,
    first_name: "Bambie",
    last_name: "Spinley",
    email: "bspinley7@apple.com",
    gender: "Female",
    "password ": "dV4'&vbg~",
  },
  {
    id: 9,
    first_name: "Fernando",
    last_name: "Blaby",
    email: "fblaby8@arizona.edu",
    gender: "Male",
    "password ": "aD5@nMbqh%/O5",
  },
  {
    id: 10,
    first_name: "Biron",
    last_name: "Curwen",
    email: "bcurwen9@examiner.com",
    gender: "Male",
    "password ": 'tL6"dr)}NhwyLxb{',
  },
];

module.exports = students;
